# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"
          extended: true
      - name: "♻️ Cache Hugo modules"
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugo-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: "🧰 Install Node"
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "14.15.4"
      - name: "♻️ Cache dependencies"
        uses: actions/cache@v2.1.4
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('assets/yarn.lock') }}
      - name: "🧰 Install asset dependencies"
        run: |
          yarn --cwd assets/ install
      - name: "🏗 Build"
        run: hugo
      - name: "🚀 Deploy to Uberspace"
        uses: appleboy/scp-action@v0.1.1
        with:
          username: familie
          host: charon.uberspace.de
          key: ${{ secrets.DEPLOY_KEY }}
          source: public
          strip_components: 1
          rm: true
          target: ${{ secrets.DEPLOY_TARGET_PATH }}
